name: va02_musicapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: AnekDevanagari
      fonts:
        - asset: assets/fonts/AnekDevanagari-Bold.ttf
        - asset: assets/fonts/AnekDevanagari-Light.ttf
        - asset: assets/fonts/AnekDevanagari-Medium.ttf
        - asset: assets/fonts/AnekDevanagari-Regular.ttf
        - asset: assets/fonts/AnekDevanagari-SemiBold.ttf



